trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    dotNetVersion: '3.0.100-preview8-013656'
    nugetVersion: '5.2.0'

  steps:
  - task: NuGetToolInstaller@0
    displayName: Install NuGet v$(nugetVersion)
    inputs:
      versionSpec: $(nugetVersion)

  - task: DotNetCoreInstaller@0
    displayName: Install Dot Net Core v$(dotNetVersion)
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

  - script: nbgv cloud
    displayName: Set Version
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

  - task: MSBuild@1
    displayName: Build Solutions
    inputs:
      solution: '$(solution)'
      msbuildVersionOption: 'latest'
      msbuildArguments: /t:build;pack /p:NoPackageAnalysis=true /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\artifacts /v:minimal /p:JavaSdkDirectory="$(JAVA_HOME)/"
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: '**/*Tests/*Windows.csproj'
      arguments: '--configuration $(buildConfiguration) --logger:"console;verbosity=detailed"'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\artifacts
      ArtifactName: artifacts
      publishLocation: Container
    condition: always()

- job: Mac
  pool:
    vmImage: 'macOS-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    dotNetVersion: '3.0.100-preview8-013656'
    nugetVersion: '5.2.0'

  steps:
  - bash: |
      SYMLINK=6_0_0
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
    displayName: Update Mono 6.0.0

  - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_0_0
    displayName: Update Xamarin SDK 6.0.0

  - task: NuGetToolInstaller@0
    displayName: Install NuGet v$(nugetVersion)
    inputs:
      versionSpec: $(nugetVersion)

  - task: DotNetCoreInstaller@0
    displayName: Install Dot Net Core v$(dotNetVersion)
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

  - script: ./nbgv cloud
    displayName: Set Version
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

  - task: MSBuild@1
    displayName: Build Solutions
    inputs:
      solution: '$(solution)'
      msbuildVersionOption: 'latest'
      msbuildArguments: /t:build /p:NoPackageAnalysis=true /v:minimal
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: '**/*Tests/*Mac.csproj'
      arguments: '--configuration $(buildConfiguration) --logger:"console;verbosity=detailed"'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
